databases:
  - name: movie_poster_classifier_db
    plan: free
    databaseName: movie_poster_classifier
    user: movie_poster_classifier

services:
  - type: web
    plan: free
    name: movie_poster_classifier
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "pipenv run daphne -b 0.0.0.0 movie_poster_classifier.asgi:application"
    envVars:
      - key: USE_POSTGRES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: movie_poster_classifier_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4